//Auth User
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADING_COMPLETE = "USER_LOADING_COMPLETE";

//Profiles
export const LOADING_TEAM_PROFILES = "LOADING_TEAM_PROFILES";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const SET_TEAM_PROFILES = "SET_TEAM_PROFILES";

//Team availability
export const LOADING_AVAILABILITY = "LOADING_AVAILABILITY";
export const SET_CURRENT_AVAILABLES = "SET_CURRENT_AVAILABLES";
export const ADD_AVAILABLE = "ADD_AVAILABLE";
export const REMOVE_AVAILABLE = "REMOVE_AVAILABLE";
export const LEFT_LIVE_CALL = "LEFT_LIVE_CALL";
export const IN_LIVE_CALL = "IN_LIVE_CALL";

//Jobs
export const LOADING_JOBS = "LOADING_JOBS";
export const SET_JOBS = "SET_JOBS";
export const UPLOAD_JOB = "UPLOAD_JOB";
export const LOAD_JOB_VIEW = "LOAD_JOB_VIEW";
