export const SET_SKYWRITER_IN_CALL = "SET_SKYWRWITER_IN_CALL";
export const SET_IS_SENDER = "SET_IS_SENDER";
export const SET_TOKEN = "SET_TOKEN";
export const CLEAR_LIVE_CALL = "CLEAR_LIVE_CALL";
export const LOADING_SKYWRITER = "LOADING_SKYWRITER";
export const FINDING_SKYWRITER_ERROR = "FINDING_SKYWRITER_ERROR";
export const SAVED_LIVECALL = "SAVED_LIVECALL";
export const CAN_PRE_SAVE = "CAN_PRE_SAVE";
export const CALL_DISCONNECTED = "CALL_DISCONNECTED";
export const SAVING_LIVECALL = "SAVING_LIVECALL";
export const CALL_FINISHED = "CALL_FINISHED";
export const SET_ROOM_INFO = "SET_ROOM_INFO";
export const SET_DESCRIPTION = "SET_DESCRIPTION";

// many replicate the socket events
export const ROOM_INITIATE = "ROOM_INITIATE";
export const CALL_ACCEPTED = "CALL_ACCEPTED";
export const SKYWRITER_ARRIVED = "SKYWRITER_ARRIVED";
export const LEAVING = "LEAVING";
export const CALL_CANCELLED = "CALL_CANCELLED";
export const CALL_REJECT = "CALL_REJECT";
export const TERMINATE_CALL = "TERMINATE_CALL";
export const NOTIFY = "NOTIFY";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const INCOMING_ROOM_CONNECT = "INCOMING_ROOM_CONNECT";
export const INCOMING_ROOM_INITIATE = "INCOMING_ROOM_INITIATE";
// These are more available context
export const IN_LIVE_CALL = "IN_LIVE_CALL";
export const LEFT_LIVE_CALL = "LEFT_LIVE_CALL";
