export const USER_CONNECTED = "USER_CONNECTED";
export const USER_CONNECTED_SUCCESS = "USER_CONNECTED_SUCCESS";
export const USER_CONNECTED_FAIL = "USER_CONNECTED_FAIL";

export const ON_USER_CONNECTED = "ON_USER_CONNECTED";
export const ON_USER_CONNECTED_SUCCESS = "ON_USER_CONNECTED_SUCCESS";
export const ON_USER_CONNECTED_FAIL = "ON_USER_CONNECTED_FAIL";

export const CONNECT = "CONNECT";
export const CONNECT_SUCCESS = "CONNECT_SUCCESS";
export const CONNECT_FAIL = "CONNECT_FAIL";

export const DISCONNECT = "DISCONNECT";
export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const DISCONNECT_FAIL = "DISCONNECT_FAIL";
