export const USER_CONNECTED = "USER_CONNECTED";
export const USER_CONNECTED_SUCCESS = "USER_CONNECTED_SUCCESS";
export const USER_CONNECTED_FAIL = "USER_CONNECTED_FAIL";

export const ON_USER_CONNECTED = "ON_USER_CONNECTED";
export const ON_USER_CONNECTED_SUCCESS = "ON_USER_CONNECTED_SUCCESS";
export const ON_USER_CONNECTED_FAIL = "ON_USER_CONNECTED_FAIL";

export const CONNECT = "CONNECT";
export const CONNECT_SUCCESS = "CONNECT_SUCCESS";
export const CONNECT_FAIL = "CONNECT_FAIL";

export const DISCONNECT = "DISCONNECT";
export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const DISCONNECT_FAIL = "DISCONNECT_FAIL";

export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const USER_DISCONNECTED_SUCCESS = "USER_DISCONNECTED_SUCCESS";
export const USER_DISCONNECTED_FAIL = "USER_DISCONNECTED_FAIL";

export const ON_USER_DISCONNECTED = "ON_USER_DISCONNECTED";
export const ON_USER_DISCONNECTED_SUCCESS = "ON_USER_DISCONNECTED_SUCCESS";
export const ON_USER_DISCONNECTED_FAIL = "ON_USER_DISCONNECTED_FAIL";

//Live call
export const ROOM_CONNECT = "ROOM_CONNECT";
export const ROOM_CONNECT_SUCCESS = "ROOM_CONNECT_SUCCESS";
export const ROOM_CONNECT_FAIL = "ROOM_CONNECT_FAIL";

export const ON_ROOM_CONNECT = "ON_ROOM_CONNECT";
export const ON_ROOM_CONNECT_SUCCESS = "ON_ROOM_CONNECT_SUCCESS";
export const ON_ROOM_CONNECT_FAIL = "ON_ROOM_CONNECT_FAIL";

export const CALL_CANCEL = "ROOM_CANCEL";
export const CALL_CANCEL_SUCCESS = "ROOM_CANCEL_SUCCESS";
export const CALL_CANCEL_FAIL = "ROOM_CANCEL_FAIL";

export const ROOM_INITIATE = "ROOM_INITIATE";
export const ROOM_INITIATE_SUCCESS = "ROOM_INITIATE_SUCCESS";
export const ROOM_INITIATE_FAIL = "ROOM_INITIATE_FAIL";

export const CALL_ACCEPT = "CALL_ACCEPT";
export const CALL_ACCEPT_SUCCESS = "CALL_ACCEPT_SUCCESS";
export const CALL_ACCEPT_FAIL = "CALL_ACCEPT_FAIL";

export const SKYWRITER_ARRIVED = "SKYWRITER_ARRIVED";
export const SKYWRITER_ARRIVED_SUCCESS = "SKYWRITER_ARRIVED_SUCCESS";
export const SKYWRITER_ARRIVED_FAIL = "SKYWRITER_ARRIVED_FAIL";
