export const USER_CONNECTED = "USER_CONNECTED";
export const USER_CONNECTED_SUCCESS = "USER_CONNECTED_SUCCESS";
export const USER_CONNECTED_FAIL = "USER_CONNECTED_FAIL";

export const ON_USER_CONNECTED = "ON_USER_CONNECTED";
export const ON_USER_CONNECTED_SUCCESS = "ON_USER_CONNECTED_SUCCESS";
export const ON_USER_CONNECTED_FAIL = "ON_USER_CONNECTED_FAIL";

export const OFF_USER_CONNECTED = "OFF_USER_CONNECTED";
export const OFF_USER_CONNECTED_SUCCESS = "OFF_USER_CONNECTED_SUCCESS";
export const OFF_USER_CONNECTED_FAIL = "OFF_USER_CONNECTED_FAIL";

export const CONNECT = "CONNECT";
export const CONNECT_SUCCESS = "CONNECT_SUCCESS";
export const CONNECT_FAIL = "CONNECT_FAIL";

export const DISCONNECT = "DISCONNECT";
export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const DISCONNECT_FAIL = "DISCONNECT_FAIL";

export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const USER_DISCONNECTED_SUCCESS = "USER_DISCONNECTED_SUCCESS";
export const USER_DISCONNECTED_FAIL = "USER_DISCONNECTED_FAIL";

export const ON_USER_DISCONNECTED = "ON_USER_DISCONNECTED";
export const ON_USER_DISCONNECTED_SUCCESS = "ON_USER_DISCONNECTED_SUCCESS";
export const ON_USER_DISCONNECTED_FAIL = "ON_USER_DISCONNECTED_FAIL";

export const OFF_USER_DISCONNECTED = "OFF_USER_DISCONNECTED";
export const OFF_USER_DISCONNECTED_SUCCESS = "OFF_USER_DISCONNECTED_SUCCESS";
export const OFF_USER_DISCONNECTED_FAIL = "OFF_USER_DISCONNECTED_FAIL";

//Live call
export const ROOM_CONNECT = "ROOM_CONNECT";
export const ROOM_CONNECT_SUCCESS = "ROOM_CONNECT_SUCCESS";
export const ROOM_CONNECT_FAIL = "ROOM_CONNECT_FAIL";

export const ON_ROOM_CONNECT = "ON_ROOM_CONNECT";
export const ON_ROOM_CONNECT_SUCCESS = "ON_ROOM_CONNECT_SUCCESS";
export const ON_ROOM_CONNECT_FAIL = "ON_ROOM_CONNECT_FAIL";

export const CALL_CANCEL = "ROOM_CANCEL";
export const CALL_CANCEL_SUCCESS = "ROOM_CANCEL_SUCCESS";
export const CALL_CANCEL_FAIL = "ROOM_CANCEL_FAIL";

//ON only event
export const ROOM_INITIATE = "ROOM_INITIATE";
export const ON_ROOM_INITIATE = "ON_ROOM_INITIATE";
export const ON_ROOM_INITIATE_SUCCESS = "ON_ROOM_INITIATE_SUCCESS";
export const ON_ROOM_INITIATE_FAIL = "ON_ROOM_INITIATE_FAIL";

export const CALL_ACCEPT = "CALL_ACCEPT";
export const CALL_ACCEPT_SUCCESS = "CALL_ACCEPT_SUCCESS";
export const CALL_ACCEPT_FAIL = "CALL_ACCEPT_FAIL";

export const ON_CALL_ACCEPT = "ON_CALL_ACCEPT";
export const ON_CALL_ACCEPT_SUCCESS = "ON_CALL_ACCEPT_SUCCESS";
export const ON_CALL_ACCEPT_FAIL = "ON_CALL_ACCEPT_FAIL";

export const SKYWRITER_ARRIVED = "SKYWRITER_ARRIVED";
export const SKYWRITER_ARRIVED_SUCCESS = "SKYWRITER_ARRIVED_SUCCESS";
export const SKYWRITER_ARRIVED_FAIL = "SKYWRITER_ARRIVED_FAIL";

export const LEAVING = "LEAVING";
export const LEAVING_SUCCESS = "LEAVING_SUCCESS";
export const LEAVING_FAIL = "LEAVING_FAIL";

export const ON_LEAVING = "ON_LEAVING";
export const ON_LEAVING_SUCCESS = "ON_LEAVING_SUCCESS";
export const ON_LEAVING_FAIL = "ON_LEAVING_FAIL";

//Terminate -- on only
export const TERMINATE_CALL = "TERMINATE_CALL";
export const TERMINATE_CALL_SUCCESS = "TERMINATE_CALL_SUCCESS";
export const TERMINATE_CALL_FAIL = "TERMINATE_CALL_FAIL";

//Reject
export const CALL_REJECT = "CALL_REJECT";
export const CALL_REJECT_SUCCESS = "CALL_REJECT_SUCCESS";
export const CALL_REJECT_FAIL = "CALL_REJECT_FAIL";

export const ON_CALL_REJECT = "ON_CALL_REJECT";
export const ON_CALL_REJECT_SUCCESS = "ON_CALL_REJECT_SUCCESS";
export const ON_CALL_REJECT_FAIL = "ON_CALL_REJECT_FAIL";

//Messages
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const ON_SEND_MESSAGE = "ON_SEND_MESSAGE";
export const ON_SEND_MESSAGE_SUCCESS = "ON_SEND_MESSAGE_SUCCESS";
export const ON_SEND_MESSAGE_FAIL = "ON_SEND_MESSAGE_FAIL";

//Alerts
export const POKE_NOTIFY = "POKE_NOTIFY";
export const POKE_NOTIFY_SUCESS = "POKE_NOTIFY_SUCCESS";
export const POKE_NOTIFY_FAIL = "POKE_NOTIFY_FAIL";

export const ON_POKE_NOTIFY = "ON_POKE_NOTIFY";
export const ON_POKE_NOTIFY_SUCCESS = "ON_POKE_NOTIFY_SUCCESS";
export const ON_POKE_NOTIFY_FAIL = "ON_POKE_NOTIFY_FAIL";

//LEFT LIVE CALL
export const LEFT_LIVE_CALL = "LEFT_LIVE_CALL";
export const LEFT_LIVE_CALL_SUCCESS = "LEFT_LIVE_CALL_SUCCESS";
export const LEFT_LIVE_CALL_FAIL = "LEFT_LIVE_CALL_FAIL";

export const ON_LEFT_LIVE_CALL = "ON_LEFT_LIVE_CALL";
export const ON_LEFT_LIVE_CALL_SUCCESS = "ON_LEFT_LIVE_CALL_SUCCESS";
export const ON_LEFT_LIVE_CALL_FAIL = "ON_LEFT_LIVE_CALL_FAIL";
